// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://errojsulkefaiwqzjpza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycm9qc3Vsa2VmYWl3cXpqcHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2NDk0MzQsImV4cCI6MjA4NDIyNTQzNH0.YerQ4d5q3mWAfSGnKcH4yUSLtCyW3nNZvdfwjG4kcUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});